"""Backfill correctly-relaxed CIFs for systems generated by the buggy pipeline.

Background
----------
Older runs of ``run_mattergen_mattersim.py`` had a bug in ``step6_save``: it
wrote the *original* (pre-relaxation) MatterGen structures to
``data/mattergen/{system}/relaxed/`` while the CSV's volume / energy /
crystal_system columns came from the post-relaxation geometry. This script
repairs the on-disk CIFs by re-running the same MatterSim relaxation on each
existing CIF and overwriting it in place. Optionally it then re-runs the
spglib classification used by ``enrich_hull_csv.py`` to refresh the
crystal_system column.

Usage
-----
    python scripts/backfill_relaxed_cifs.py --system Ni-Bi
    python scripts/backfill_relaxed_cifs.py --all          # repair every system
    python scripts/backfill_relaxed_cifs.py --system Ni-Bi --refresh-csv
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from ase.filters import FrechetCellFilter
from ase.optimize import LBFGS
from pymatgen.core import Structure
from pymatgen.io.ase import AseAtomsAdaptor
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))

from hullgap.calculators import get_calculator  # noqa: E402

RESULTS_DIR = PROJECT_ROOT / "data" / "results"
MATTERGEN_DIR = PROJECT_ROOT / "data" / "mattergen"

logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(message)s",
                    datefmt="%H:%M:%S")
log = logging.getLogger(__name__)


def relax_in_place(cif_path: Path, calc, fmax: float = 0.02,
                   max_steps: int = 500) -> dict:
    """Re-relax the structure in ``cif_path`` and overwrite it.

    Returns a dict with ``volume_A3``, ``e_total_eV``, ``e_per_atom_eV``,
    ``fmax_eV_A``, ``status`` from the post-relaxation state.
    """
    struct = Structure.from_file(str(cif_path))
    atoms = AseAtomsAdaptor.get_atoms(struct)
    atoms.calc = calc

    opt = LBFGS(FrechetCellFilter(atoms), logfile=None)
    opt.run(fmax=fmax, steps=max_steps)

    e_total = float(atoms.get_potential_energy())
    n_atoms = len(atoms)
    fmax_val = float(np.max(np.linalg.norm(atoms.get_forces(), axis=1)))
    status = "converged" if fmax_val < fmax else "max_steps"

    relaxed = AseAtomsAdaptor.get_structure(atoms)
    relaxed.to(filename=str(cif_path))  # overwrite in place

    return {
        "volume_A3": atoms.get_volume(),
        "e_total_eV": e_total,
        "e_per_atom_eV": e_total / n_atoms,
        "fmax_eV_A": fmax_val,
        "status": status,
    }


def repair_system(system: str, calc, refresh_csv: bool) -> None:
    relaxed_dir = MATTERGEN_DIR / system / "relaxed"
    csv_path = RESULTS_DIR / f"{system}_mattersim_hull.csv"

    if not relaxed_dir.is_dir():
        log.warning("[%s] no relaxed/ dir, skipping", system)
        return
    cifs = sorted(relaxed_dir.glob(f"{system}_*.cif"))
    if not cifs:
        log.warning("[%s] no CIFs in %s, skipping", system, relaxed_dir)
        return

    log.info("[%s] re-relaxing %d CIFs ...", system, len(cifs))
    refreshed: dict[int, dict] = {}
    for cif in cifs:
        try:
            idx = int(cif.stem.split("_")[1])
        except (IndexError, ValueError):
            log.warning("  skip %s (cannot parse idx)", cif.name)
            continue
        try:
            stats = relax_in_place(cif, calc)
            refreshed[idx] = stats
            log.info("  [%d] %-22s  E=%.4f eV/at  V=%.2f Å³  %s",
                     idx, cif.name, stats["e_per_atom_eV"],
                     stats["volume_A3"], stats["status"])
        except Exception as exc:
            log.error("  [%d] FAILED on %s: %s", idx, cif.name, exc)

    if refresh_csv and csv_path.exists():
        log.info("[%s] refreshing CSV columns ...", system)
        df = pd.read_csv(csv_path)
        for col in ("volume_A3", "e_total_eV", "e_per_atom_eV",
                    "fmax_eV_A", "crystal_system"):
            if col not in df.columns:
                df[col] = np.nan if col != "crystal_system" else "Unknown"

        for i, row in df.iterrows():
            idx = int(row["idx"])
            if idx in refreshed:
                df.at[i, "volume_A3"] = refreshed[idx]["volume_A3"]
                df.at[i, "e_total_eV"] = refreshed[idx]["e_total_eV"]
                df.at[i, "e_per_atom_eV"] = refreshed[idx]["e_per_atom_eV"]
                df.at[i, "fmax_eV_A"] = refreshed[idx]["fmax_eV_A"]
            cif_match = sorted(relaxed_dir.glob(f"{system}_{idx:03d}_*.cif"))
            if cif_match:
                try:
                    s = Structure.from_file(str(cif_match[0]))
                    cs = SpacegroupAnalyzer(s, symprec=0.1).get_crystal_system()
                    df.at[i, "crystal_system"] = (cs or "Unknown").capitalize()
                except Exception as exc:
                    log.warning("  spglib failed on idx=%d: %s", idx, exc)

        # NB: e_form_eV_atom and e_above_hull_eV_atom depend on elemental
        # references; recomputing them is out of scope here. They were
        # already computed from the (correct) relaxed energies, so they
        # remain valid as long as relaxation lands on the same minimum.
        df.to_csv(csv_path, index=False)
        log.info("[%s] wrote refreshed CSV: %s", system, csv_path)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    g = parser.add_mutually_exclusive_group(required=True)
    g.add_argument("--system", help='e.g. "Ni-Bi"')
    g.add_argument("--all", action="store_true",
                   help="repair every system under data/mattergen/")
    parser.add_argument("--model", default="mattersim",
                        help="MLIP calculator name (default: mattersim)")
    parser.add_argument("--device", default=None,
                        help="cuda | cpu (default: auto-detect)")
    parser.add_argument("--refresh-csv", action="store_true",
                        help="also rewrite the CSV's volume / energy / "
                             "crystal_system columns from the new CIFs")
    args = parser.parse_args()

    device = args.device
    if device is None:
        try:
            import torch
            device = "cuda" if torch.cuda.is_available() else "cpu"
        except ImportError:
            device = "cpu"
    log.info("Using calculator '%s' on device %s", args.model, device)
    calc = get_calculator(args.model, device=device)

    if args.all:
        systems = sorted(p.name for p in MATTERGEN_DIR.iterdir()
                         if p.is_dir() and (p / "relaxed").is_dir())
    else:
        systems = [args.system]

    for system in systems:
        repair_system(system, calc, refresh_csv=args.refresh_csv)

    log.info("Done")


if __name__ == "__main__":
    main()
